site_name: Dmitry Fedoreev
site_url: https://dmitry.github.io/blog/
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Главная: index.md
  - Статьи:
      - Контент-маркетинг: articles/article1.md
      - Успешные кейсы в SMM: articles/article2.md
      - SEO для малого бизнеса: articles/article3.md